force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Sensor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor__c/fields/Sensor_model__c.field-meta.xml
<CustomField>
    <fullName>Sensor_model__c</fullName>
    <label>Sensor model</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sensor__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static Id createTestCSVFile(String data){
        ContentVersion testContentVersion = new ContentVersion(
            Title = 'Sensors',
            PathOnClient = 'Sensors',
            VersionData = Blob.valueOf(data),
            IsMajorVersion = true
        );
        insert testContentVersion;
        System.debug(testContentVersion);
        List<ContentVersion> contentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Title = 'Sensors' LIMIT 1];
        System.debug(contentId[0].ContentDocumentId);
        return contentId[0].ContentDocumentId;
    }

    public static List<Sensor__c> createSensors(String model, String status, Integer count){
        List<Sensor__c> sensorList = new List<Sensor__c>();
        for(Integer i = 0; i<count; i++){
            Sensor__c sensor = new Sensor__c(Sensor_model__c = model, Status__c = status);
            sensorList.add(sensor);
        }
        
        if(!sensorList.isEmpty()){
            insert sensorList;
            return sensorList;
        }
        else{
            return null;
        }
       
    }
}