force-app/main/default/objects/Base_Station__c/Base_Station__c.object-meta.xml
<CustomObject>
    <label>Base Station</label>
    <nameField>
        <label>Base Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Station__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Broken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Sensor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor__c/fields/Base_Station__c.field-meta.xml
<CustomField>
    <fullName>Base_Station__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Station</label>
    <referenceTo>Base_Station__c</referenceTo>
    <relationshipLabel>Sensors</relationshipLabel>
    <relationshipName>Sensors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sensor__c/fields/Sensor_model__c.field-meta.xml
<CustomField>
    <fullName>Sensor_model__c</fullName>
    <label>Sensor model</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sensor__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SensorManagementControllerTest.cls
@isTest
private class SensorManagementControllerTest {
    @testSetup
    static void prepareTestData(){
        List<Base_Station__c> testStations = new List<Base_Station__c>();
        testStations.add(new Base_Station__c(Name = 'Earth', Status__c = 'Active'));
        testStations.add(new Base_Station__c(Name = 'Uranus', Status__c = 'Inactive'));
        testStations.add(new Base_Station__c(Name = 'Neptune', Status__c = 'Broken'));
        insert testStations;
    }

    
    @isTest static void testReadCSVDataPositiveCase(){
        String testData = 'Sensor_model__c,Status__c,Base_Station__c\n' +
                            'Tambee,Inactive,Earth\n' +
                            'Wordify,Inactive,Uranus\n' +
                            'Topicstorm,Active, ';

        String fileId = TestDataFactory.createTestCSVFile(testData);                
        List<Sensor__c> resultDataList = SensorManagementController.readCSVData(fileId);
        System.assertEquals(3, resultDataList.size());

    }

    @isTest static void testReadCSVDataEmptySensorModelExceptionCase(){
        String testData = 'Sensor_model__c,Status__c,Base_Station__c\n' +
                            ' ,Inactive,Earth';

        String fileId = TestDataFactory.createTestCSVFile(testData); 
        Boolean occuredException = false;
        try{
            SensorManagementController.readCSVData(fileId);
        }
        catch(Exception ex){
            occuredException = true;
        }
        System.assert(occuredException, 'Expected empty Sensor Model field exception');
    }

    @isTest static void testReadCSVDataInvalidStatusExceptionCase(){
        String testData = 'Sensor_model__c,Status__c,Base_Station__c\n' +
                            'Aleksey,Broken,Earth';
        String fileId = TestDataFactory.createTestCSVFile(testData); 
        Boolean occuredException = false;
        try{
            SensorManagementController.readCSVData(fileId);
        }
        catch(Exception ex){
            occuredException = true;
        }
        System.assert(occuredException, 'Expected invalid Status field exception');
    }

    @isTest static void testReadCSVDataNullDocumentIdExceptionCase(){
        Boolean occuredException = false;
        try{
            SensorManagementController.readCSVData(null);
        }
        catch(Exception ex){
            occuredException = true;
        }
        System.assert(occuredException, 'Expected null Document Id exception');
    }

    @isTest static void testReadCSVGeneralExceptionCase(){
        Boolean occuredException = false;
        try{
            Id fakeId = '0685j000002pinGAAQ';
            SensorManagementController.readCSVData(fakeId);
        }
        catch(Exception ex){
            occuredException = true;
        }
        System.assert(occuredException, 'Expected Script-throw exception');
    }
    
    @isTest static void testDeleteSensorPositiveCase(){
        Sensor__c sensor = new Sensor__c(Sensor_model__c = 'model', Status__c = 'Inactive');
        insert sensor;
        System.debug('Sensor: ' + [SELECT Id, Sensor_model__c FROM Sensor__c WHERE Id =: sensor.Id]);
        SensorManagementController.deleteSensor(sensor.Id);
        List<Sensor__c> checkSensorList = [SELECT Id, Sensor_model__c FROM Sensor__c WHERE Id =: sensor.Id];
        System.assertEquals(0,checkSensorList.size());

    }

    @isTest static void testDeleteSensorNullIdExceptionCase(){
        Boolean occuredException = false;
        try{
            SensorManagementController.deleteSensor(null);
        }
        catch(Exception ex){
            occuredException = true;
        }
        System.assert(occuredException, 'Expected invalid Id exception');
    }

    @isTest static void testDeleteSensorInvalidIdExceptionCase(){
        Boolean occuredException = false;
        try{
            Id fakeId = '0685j000002pinGAAQ';
            SensorManagementController.deleteSensor(fakeId);
        }
        catch(Exception ex){
            occuredException = true;
        }
        System.assert(occuredException, 'Expected invalid Id exception');
    }

    @isTest static void testGetSensors(){
        TestDataFactory.createSensors('test', 'Inactive', 15);
        List<Sensor__c> sensorList = SensorManagementController.getSensors(0, 10);
        System.assertEquals(10,sensorList.size());

    }

    @isTest static void testGetCountSensors(){
        TestDataFactory.createSensors('test', 'Inactive', 15);
        Integer count = SensorManagementController.getCountSensors();
        System.assertEquals(15,count);

    }
   
}