force-app/main/default/objects/Base_Station__c/Base_Station__c.object-meta.xml
<CustomObject>
    <label>Base Station</label>
    <nameField>
        <label>Base Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Station__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Broken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Sensor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor__c/fields/Base_Station__c.field-meta.xml
<CustomField>
    <fullName>Base_Station__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Station</label>
    <referenceTo>Base_Station__c</referenceTo>
    <relationshipLabel>Sensors</relationshipLabel>
    <relationshipName>Sensors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sensor__c/fields/Sensor_model__c.field-meta.xml
<CustomField>
    <fullName>Sensor_model__c</fullName>
    <label>Sensor model</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sensor__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/sensorManagementController.cls
public with sharing class SensorManagementController {
    public virtual class BaseException extends Exception {}
    public class SensorsListException extends BaseException {}
    public class DocumentException extends BaseException {}

    @AuraEnabled
    public static List<Sensor__c> readCSVData(Id contentDocumentId){
        List<Sensor__c> sensorList = new List<Sensor__c>();
        try {
            if(contentDocumentId != null){
                ContentVersion contentVersionObj = [SELECT Id, VersionData FROM ContentVersion WHERE ContentDocumentId =:contentDocumentId];
                List<String> csvRecordList = contentVersionObj.VersionData.toString().split('\n');
                List<Base_Station__c> stations =  [SELECT Id, Name FROM Base_Station__c Order by Name];
                for(Integer i = 1; i < csvRecordList.size(); i++){
                    Sensor__c newSensor = new Sensor__c();
                    List<String> csvRowList = csvRecordList[i].split(',');
                    System.debug('csvRow: '+ csvRowList);
                    newSensor.Sensor_model__c = csvRowList[0];
                    newSensor.Status__c = csvRowList[1];
                    if(csvRowList[2].trim() != null){
                        for(Base_Station__c station : stations){
                            System.debug('csvRowList[2]: ' + csvRowList[2]);
                            if(station.Name == csvRowList[2].trim()){
                                newSensor.Base_Station__c = station.Id;
                            }
                        }
                    }
                    else {
                        newSensor.Base_Station__c = null;
                    }
                    
                    sensorList.add(newSensor);
                }
                
                if(!sensorList.isEmpty()) {
                    insert sensorList;
                }
            }
            else{
                throw new DocumentException('No dowloaded files');
            }

        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
        return sensorList;
    }

    @AuraEnabled
    public static void deleteSensor(Id sensorId){
        try{
            System.debug(sensorId);
            if(sensorId!=null){
                Sensor__c sensor = new Sensor__c(Id = sensorId);
                delete sensor;
            }
            else{
                throw new SensorsListException('No found selected sensor id');
            }
        }
        catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled(cacheable = true)
    public static List<Sensor__c> getSensors(Integer tableOffset, Integer tableSize){
        return [SELECT Id, Name, Sensor_Model__c, Status__c, Base_Station__c, Base_Station__r.Name FROM Sensor__c LIMIT :tableSize OFFSET :tableOffset ];
    }

    @AuraEnabled(cacheable = true)
    public static Integer getCountSensors(){
        return [SELECT COUNT() FROM Sensor__c];
    }

}